### PR TITLE
Fix Windows volume bindings for Rancher, Podman and Windows-based containers

### LINKED ISSUE #1719: Windows volume bindings do not work correctly with Rancher Desktop or Podman
### Description
The docker-maven-plugin currently turns all Windows file paths (C:\Users\example/test.txt) into /c/Users/example/test.txt in [EnvUtils.fixupPath](https://github.com/fabric8io/docker-maven-plugin/blob/f228f644e6ec945f9bdea037980db16a9bab28f7/src/main/java/io/fabric8/maven/docker/util/EnvUtil.java#L347).

This leads to problems when using Rancher Desktop or Podman instead of Docker Desktop. Since both of these tools only run in the WSL, the correct path in the WSL image would be /mnt/c/Users/example/test.txt . The /mnt/ part is currently missing.

However, both Rancher Desktop and Podman can already correct Windows paths into WSL paths if you call the Docker API with Windows file paths. So for example, `docker run -d --name nginx -v C:\Users\example\test.txt:/tmp/test.txt nginx:latest` works.

Rancher Desktop and Podman have different behavior right now with the latest docker-maven-plugin release:
- Rancher Desktop creates an empty directory under /c/Users/example/test.txt
- Podman fails with `make cli opts(): making volume mountpoint for volume /c/Users/example/test.txt: mkdir /c: permission denied`

This bug is somewhat related to #1713 

### Info

* docker-maven-plugin version : 0.43.4
* Maven version (`mvn -v`) :
```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: C:\Development\maven
Java version: 11.0.14.1, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-11.0.14.1+1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
* Docker version : Rancher Desktop 1.8.1, Podman 4.7.2
* If it's a bug, how to reproduce :
  1. Install and start Podman on Windows using this guide: https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md
  2. If `podman pull nginx` does not work, you probably have to fix the DNS resolution in the WSL image with this fix: https://gist.github.com/ThePlenkov/6ecf2a43e2b3898e8cd4986d277b5ecf
  3. Clone the sample project
  4. Run `mvn verify`, it should fail with the `permission denied` error
* Sample project : *[GitHub Clone URL](https://github.com/bergerst/docker-plugin-windows-showcase.git)*

### PR DESCRIPTION
**Pull request by bergerst**
Fixes #1719 #1713

After my fix, the sample provided in #1719 works.

### CODE REVIEW

**Comment by bergerst** [comment]
@rohanKanojia I've fixed the test failures and tested the changes both on Linux- and Windows-based containers.

Can you please trigger the Github workflows again and review my changes?

**Comment by bergerst** [comment]
Test coverage should be better now after the 2nd commit. I can squash my commits if you want, but I thought reviewing will be easier if the commits are split.

I converted the existing for-loop tests into ParameterizedTests since it's easier to read. The ulimit tests in ContainerHostConfigTest were broken since they only read `data[1]`, `data[2]` and so on instead of `data[i+1]` and `data[i+2]`

**Comment by bergerst** [comment]
Sorry, now all tests should pass again.

**Comment by rhuss** [comment]
Thanks! This looks good to me. Could you add some notes to https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md for this bug ? Otherwise it looks good for me to merg.

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
I'll add an entry to the changelog while preparing for the next release.

**Pull request merged**
