### PR TITLE
Wait for request.abort to finish before calling is.close();

### LINKED ISSUE #1103: docker:start always blocks on windows
### Description
Whenever I use docker:start on windows it's always blocking build execution although docker container was successfully started and wait condition satisfied.

I'm using the latest plugin version. I tried explicitly specify docker.follow=false - didn't help. The same config works fine with docker for OSX.

### Info

* d-m-p version : 0.27.1
* Maven version (`mvn -v`) : 3.5.4
* Docker version : 18.06.1-ce-win73
* If it's a bug, how to reproduce :
My docker execution config looks like this:

```
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.27.1</version>
                <configuration>
                    <images>
                        <image>
                            <name>localstack/localstack:0.8.7</name>
                            <run>
                                <env>
                                    <SERVICES>dynamodb</SERVICES>
                                </env>
                                <ports>
                                    <port>4569:4569</port>
                                </ports>
                                <log/>
                                <wait>
                                    <log>^Ready\.$</log>
                                </wait>
                            </run>
                        </image>
                    </images>
                    <skip>${skipTests}</skip>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>start</goal>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
then execution docker:start -X will show that waitcondition was met, execution returned 0 and then process hangs.

### PR DESCRIPTION
**Pull request by ncelerier**
Trying to fix #1103.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
For me LogRequestorTest seems to be stuck on Linux:
```
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.fabric8.maven.docker.access.ContainerHostConfigTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 s - in io.fabric8.maven.docker.access.ContainerHostConfigTest
[INFO] Running io.fabric8.maven.docker.access.hc.DockerAccessWithHcClientTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.346 s - in io.fabric8.maven.docker.access.hc.DockerAccessWithHcClientTest
[INFO] Running io.fabric8.maven.docker.access.hc.HcChunkedResponseHandlerWrapperTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 s - in io.fabric8.maven.docker.access.hc.HcChunkedResponseHandlerWrapperTest
[INFO] Running io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegateTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.091 s - in io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegateTest
[INFO] Running io.fabric8.maven.docker.access.ecr.AwsSigner4RequestTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 s - in io.fabric8.maven.docker.access.ecr.AwsSigner4RequestTest
[INFO] Running io.fabric8.maven.docker.access.ecr.EcrExtendedAuthTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 s - in io.fabric8.maven.docker.access.ecr.EcrExtendedAuthTest
[INFO] Running io.fabric8.maven.docker.access.log.LogRequestorTest

```

**Comment by ncelerier** [comment]
Indeed, I have the same problem, I should have run the tests. finish() is not called so the request is never null and it keeps looping. 

Does it at least work when you launch a container ?

**Comment by ncelerier** [comment]
I see you don't have `*** Calling is.close...` that is displayed, so I tried multiple time and sometimes I see it, sometimes not ...

But as discussed in #1031, if request.abort() is closing the InputStream, we can remove the finally block. Then the tests are green and when I launch my application and Sim4Y one, it works. Can you try that?

**Comment by rohanKanojia** [comment]
You're right. Removing `finally` block seems to fix tests and SimY's sample for me as well.

**Comment by ncelerier** [comment]
I have just pushed a new commit that remove the finally block as it seems it is the best solution for now.

**Comment by rohanKanojia** [comment]
There is a minor code smell regarding an unused import. Could you please address it whenever you revisit this? I'll check if we can add integration tests for windows. Github actions do provide windows VMs, but I don't know if they have docker installed or not.

**Comment by ncelerier** [comment]
Indeed, I have fix it.

**Comment by rohanKanojia** [comment]
@SimY4: polite ping, Would it be possible for you to build snapshot version of this PR and try it on your windows setup :pray: ? I'm trying to reproduce this with [a windows github action workflow](https://github.com/r0haaaan/ImmutablesDynamoDBMapperPOC/runs/3185286418?check_suite_focus=true) but I'm struggling with it :-(

**Comment by SimY4** [comment]
@rohanKanojia @ncelerier 's PR branch seems to have no issues with my windows setup. I ran it a few times with JDK 11 and JDK 16, the latest docker for windows. The same machine where the problem was reproduced initially.

**Comment by rohanKanojia** [comment]
@SimY4 : Thanks a lot for your time. If everything is okay on your side, Could you please approve this PR? I can then proceed to merge it.

**Comment by SimY4** [comment]
@rohanKanojia no worries. I'm glad I could help. 

I don't have a handle to approve, I'm not a contributor. But LGTM. 👍

**Review by rohanKanojia — APPROVED** [review]

**Comment by rkhmelichek** [comment]
@rohanKanojia can a new build be released incorporating these latest changes?
The last release currently logs some errors (although harmless) on `close()` of the InputStream because it follows `abort()`:
`IO Error while requesting logs: jnr.enxio.channels.NativeException: Bad file descriptor Thread-5`

FYI this error is logged only on Docker Desktop for Mac.
Running tests on Linux I do not get this error.
I tested with the latest changes and I do not get any errors logged on my Mac.

**Comment by rohanKanojia** [comment]
@rkhmelichek : Thanks for trying it out. I'll try to cut a new release this weekend.

**Pull request merged**
