### PR TITLE
#917 additional verbose-level logging on docker PUT/POST/DELETE

### PR DESCRIPTION
**Pull request by kennymacleod**
As described in #917 it'd be most excellent to perform verbose-level logging when we issue commands to the docker daemon. This is extremely useful when reconciling the maven plugin configuration against what the plugin is actually issuing to docker.

Currently, the verbose=true option isn't used for much of anything other than logging image build commands.

### CODE REVIEW

**Comment by rhuss** [comment]
@kennymacleod I agree, that -X is definitely too verbose as this is also used by the underlying HTTP service for logging all traffic. However, the POST requests can get quite verbose, too, and tbh I consider them more an internal implementation detail useful mostly for debugging the plugin itself (not a concrete build). E.g. the Docker CLI prints out build steps, but API communication only at higher logging levels. 

Wdyt about introducing an dedicated 'docker.verbose.api'  parameter, or even better using a value for `docker.vebose` like in `-Ddocker.verbose=build,api` ? (with `build` as the default ?)

**Comment by kennymacleod** [comment]
Yeah, I like that idea. Requires more changes to the logging code, obviously, but that would be a nicer solution.

**Comment by rhuss** [comment]
@kennymacleod ok, let's go this road then. Unfortunately I'm a bit loaded these days, but if you feel fancy, I would happily integrate the PR (typically at the weekends).

**Comment by rhuss** [comment]
@rohanKanojia I think the idea mention in https://github.com/fabric8io/docker-maven-plugin/pull/918#issuecomment-355582761 is still valid, but needs to be implemented. It's not a big deal, though, so if you want to give it a try, that would be awesome.

**Comment by rhuss** [comment]
This feature has been implemented with #1192, so closing this PR

**Pull request closed without merging**
