### PR TITLE
Issue #1195 Remove Windows file name validations.

### PR DESCRIPTION
**Pull request by wrosenuance**
The Windows file name validations were inconsistent with other platform
behaviour and impede the creation of cross-platform POMs.

Signed-off-by: William Rose <william.rose@nuance.com>

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks for the PR ! However, I'm pretty sure we added that for some reason (i.e. because of a bug on Windows). Let me find the corresponding issue ...

**Comment by rhuss** [comment]
Actually this change came in with https://github.com/fabric8io/docker-maven-plugin/pull/834 where it was exactly introduced to *fix* test failures on windows. So now I'm not sure anymore ;-)

**Comment by wrosenuance** [comment]
Yeah, I think it may have been the wrong fix for the test case. The one test case that fails without this check is the one I changed in [here](https://github.com/fabric8io/docker-maven-plugin/pull/1198/commits/7b6cb75c26f563eb70d2ad94e0ca66f36f79b92e#diff-d4e798be801faf7be6bbb66640c20d2f), and I think it's because the test tries to create an absolute path but did so in a non-portable way. Rather than making the test case create an absolute path portably, the workaround was to trigger an error for a different reason.

**Comment by rhuss** [comment]
Sounds legit. @rohanKanojia wdyt ? From my side, I think we can merge.

**Comment by rohanKanojia** [comment]
+1

मंगल, 9 अप्रैल 2019, 23:19 को Roland Huß <notifications@github.com> ने लिखा:

**Pull request merged**
