### PR TITLE
Don't fail build if volume-clean fails.

### PR DESCRIPTION
**Pull request by KedneckInc**
This fix is admittedly simplistic.  It does not take into account any of the other possible causes for an exception.  However, if you are using volume-clean, chances are you're using volume-create, or many of the other goals provided by DMP.  In that case, you will almost certainly receive errors pointing you at the
real problem.

### CODE REVIEW

**Comment by rhuss** [comment]
Sorry, for coming back to this PR that late. However,  it seems to be broken to me when you look into the list of changes and touched files. The conflicts are because we moved on, but the original changeset is still too huge to even review it. 

I'm going to close this PR therefore, it would be awesome if you create a new PR. Alternatively, if you describe the problem in a GitHub issue we could try to find a solution together.

Again sorry for the very late response.

**Comment by rhuss** [comment]
I cherry picked your change now, should be clean again.

**Comment by rhuss** [comment]
I just allowed 404 as a valid response code for a volume delete operation. This is returned when the volume does not exists. I think this is the better solution.

**Comment by KedneckInc** [comment]
Wunderbar!  I'll give it a look because I finally got back to that part of the project!

**Comment by KedneckInc** [comment]
Sorry I took so long to get back to this.  Yes, this definitely fixed the problem.  Many Thanks!  Now our developers don't have to manually clean up the old volumes!

**Pull request merged**
