### PR TITLE
Upgrade jnr-unixsocket version to 0.21

### PR DESCRIPTION
**Pull request by pvaduva**
jnr-unixsocket version 0.20 added arm64 support
si in otder to have the plugin working on arm64
we will need that version

### CODE REVIEW

**Comment by rhuss** [comment]
@pvaduva Thanks for the PR ! I have to check it because the last time I tried to update to 0.19 it was a mess breaking all sort of things.

But if it works ok for and maybe also some other issues we had with the jnr-unixsocket which mixed up parallel connections, then we will merge it for sure.

I hope I can do some experiments over the weekend.

**Comment by pvaduva** [comment]
> @pvaduva Thanks for the PR ! I have to check it because the last time I tried to update to 0.19 it was a mess breaking all sort of things.
> 
> But if it works ok for and maybe also some other issues we had with the jnr-unixsocket which mixed up parallel connections, then we will merge it for sure.
> 
> I hope I can do some experiments over the weekend.

Thanks for looking to it, Please tell me if there's anything I can do to help. 
If it does not work with the new version is there any way we can integrate 
arm64 support ? (Adding them to a fork from jnr-unixsocket 0.12 for example)

Best Regards.

**Comment by pvaduva** [comment]
Hi Roland,

Did you had time to check the upgrade of jnr-unixsocket ?

Thanks,
Paul

**Comment by gbloisi** [comment]
In the meanwhile a 0.21 version has been released, just come to this because I'm facing issue #552 too.

**Comment by rhuss** [comment]
Ok, lets try it. I did some brief sanity checks and it looks good so far. Hopefully the issues we had the Unix socker are resolved.

I'm planning a release later this week.

**Pull request merged**
