### PR TITLE
Change parent class of PushMojo for extensibility in FMP

### PR DESCRIPTION
**Pull request by dev-gaur**
Required for https://github.com/fabric8io/fabric8-maven-plugin/pull/1766

### CODE REVIEW

**Comment by dev-gaur** [comment]
I need this change to mainly use this function https://github.com/fabric8io/fabric8-maven-plugin/pull/1766/files#diff-f4deed68ba4152f427512c27f7e17e8cR176 in the pushmojo in FMP.

**Comment by dev-gaur** [comment]
> Sorry, but I'm not sure about this change.
> 
> Have tested whether it's breaking this plugin's functionality? I suspect it's disabling some things for PushMojo which might be breaking change for existing users.

@rohanKanojia I encourage you to please test it to your satisfaction and feed me back.

https://github.com/fabric8io/docker-maven-plugin/pull/1309#pullrequestreview-328206819

You're literally doing the same thing in your PR.

**Comment by rohanKanojia** [comment]
looks like I also overlooked this. I think I've done wrong changes.

**Comment by rohanKanojia** [comment]
I tested this and looks like my suspicion was wrong. push goal seems to be running fine. I had concern about dropping all the properties from AbstractDockerMojo(maybe because I come from C++ backgroud that's why), but seems like here they are accessible across the package.

I apologize for the confusion.

**Comment by dev-gaur** [comment]
np mate. how do we move forward on this?

**Pull request closed without merging**
