### PR TITLE
set SHELL from build config

### LINKED ISSUE #1418: allow specify SHELL by plugin build configuration
### Description

SHELL specified by plugin build configuration is ignored.

### Info

* d-m-p version : 0.34.0
* Maven version (`mvn -v`) : 3.6.3

### PR DESCRIPTION
**Pull request by omyl**
resolve #1418

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks ! I added a unit test + chagnelog entry, could open up your branch so that I could push to it (and we then can merge it after this)

**Comment by omyl** [comment]
> 
> 
> ...  could please open up your branch so that I could push to it (and we then can merge it after this) ....
@rhuss - hope its done (unfortunatelly i'm still not familiar with github :-/)

**Comment by rhuss** [comment]
nope, doesn't work yet. You need to enable the checkbox on the right column in the GitHub UI when looking at the PR. It should look like:

image

**Comment by rhuss** [comment]
sorry my bad. works now.

**Pull request merged**
