### PR TITLE
Support docker SHELL setting for runCmds

### LINKED ISSUE #1156: runCmds are only executable with /bin/sh set
### Description
I am trying to create a docker image with `RUN` parameters and a linux distribution as `FROM` param, that hasn't linked `/bin/sh`. Dockerfiles support two `RUN` syntaxes to set the executable that should  your command or to use the standard shell (`/bin/sh`). (https://docs.docker.com/engine/reference/builder/#run).

When you are in the situation that `/bin/sh` is not linked you are in a deadlock situation with the plugin. You need a RUN cmd to link the shell but you can't execute the link command.

I can think of two possible solutions:
1. Extend the runCmd section to support the exec syntax
2. Support the SHELL param to set a standard shell without linking it per RUN parameter (https://docs.docker.com/engine/reference/builder/#shell)

If I didn't miss something, I can make a pull request if you tell me which of the options you would prefer.

### PR DESCRIPTION
**Pull request by MeiSign**
Fixes #1156

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks ! Looks good to me, except that I would use `<shell>` as top-level element and `<arg>` (as we use it for an <exec> entrypoint, too) as configuration elements.

Could you update these please?

**Comment by MeiSign** [comment]
@rhuss I was thinking about using the args but args give the option to be outputted in exec syntax if I understood the code correctly. The shell command in a dockerfile doesn’t allow that unfortunately: “The SHELL instruction must be written in JSON form in a Dockerfile.”

Should I try to extend the args to work only with Json format with shell?

**Comment by MeiSign** [comment]
I don't mean to rush you but any opinions on my changes?

**Comment by tcompart** [comment]
with which release is this change included or when will it be merged into master?

**Comment by rhuss** [comment]
@tcompart I plan to make a release over the weekend. Sorry for the delay.

**Comment by tcompart** [comment]
thank @rhuss

**Pull request merged**
