### PR TITLE
allow multiple subcomponents in image names

### PR DESCRIPTION
**Pull request by dweomer**
Fix for #459

### CODE REVIEW

**Comment by rhuss** [comment]
ok to test

**Comment by rhuss** [comment]
thanks a lot ;-). Merge was a bit fast (we changed a bit the workflow). 'will have a review nevertheless soon ;-0

**Comment by dweomer** [comment]
Glad to help. When can I expect this to lang in Maven Central?

**Comment by rhuss** [comment]
going to make a release this week. so probably tomorrow ;-)

**Pull request merged**
