### PR TITLE
#524 Add support for passing security options to docker

### PR DESCRIPTION
**Pull request by gschulze**
Implemented support for adding security options via <securityOpt> tag.

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks, will review it soon. Would you mind to add some documentations, too ? You find them in src/main/asciidoc and you can recreate the documentation with `mvn -Pdoc-html` from the root dir.

Thanks !

**Comment by gschulze** [comment]
Sure!

**Comment by rhuss** [comment]
Thanks, looks good to me ! 

I changed the property to `securityOpts` (plural) as it is a list. I know, Docker used `SecurityOpt` for this list, but this is imo an error we should not replicate.

I'll do a release today, including your change.

Thanks again !

**Comment by gschulze** [comment]
That was fast! Thanks!

**Pull request closed without merging**
