### PR TITLE
Add ContainerNetworking section with Aliases for custom networks

### LINKED ISSUE #466: Support Net Aliases
In Docker 1.10 you can set multiple net aliases for a container to be reached (inside user created network):
https://docs.docker.com/engine/userguide/networking/configure-dns/

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container
(The last part of the creation JSON, NetworkingConfig)

### PR DESCRIPTION
**Pull request by danielwegener**
Fixes #466

Signed-off-by: Daniel Wegener <daniel@wegener.me>

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks, I will have a look at it ASAP !

**Comment by danielwegener** [comment]
Um I guess I should have created the MR against integration.

**Comment by rhuss** [comment]
No Problem. I'm just integrating it, and found out that its nicer to have a dedicated `<network>` subsection like in 

```xml
<network>
  <mode>custom</mode>
  <name>my-network</name>
  <alias>name1</alias>
  <alias>name2</alias>
</network>
```

I'm nearly finished and plan a release today. Thanks a lot for your PR, this was a very good starting point.

**Comment by rhuss** [comment]
BTW if a `<name>...</name>` is given then the default mode is _custom_

**Comment by danielwegener** [comment]
Great to hear that! I think supporting multiple networks would still be a another step, right?

**Comment by rhuss** [comment]
Yes, thats another beast ;-)

**Comment by danielwegener** [comment]
Cool. Going to prepare my poms for the upgrade :) I'll close this PR then.

**Comment by rhuss** [comment]
@danielwegener just pushed. I updated your sample with the new syntax.

Thanks again ... now i'm doing the release.

**Comment by rhuss** [comment]
0.15.13 is about to appear at maven central any time soon, heres the updated documentation --> https://fabric8io.github.io/docker-maven-plugin/#network-configuration

**Pull request closed without merging**
