### PR TITLE
Fix #1148: Proxy settings are ignored (initial draft)

### LINKED ISSUE #1148: Proxy settings are ignored
### Description
[Since Docker 17.07](https://docs.docker.com/network/proxy/) you can configure the client to use a proxy. 
When running build via d-m-p it doesn't work.

See linked project on how to reproduce.

### Info

* d-m-p version : 0.27.2
* Maven version (`mvn -v`) : 3.5.4
* Docker version : 18.06.1-ce
* Sample project : https://github.com/jakub-bochenski/demp-link-problem/tree/proxy

### PR DESCRIPTION
**Pull request by rohanKanojia**
Make BuildService read local ~/.docker/config.json directory and fetch
proxy settings.
Fixes #1148

### CODE REVIEW

**Comment by rohanKanojia** [comment]
I followed steps mentioned in https://github.com/jakub-bochenski/demp-link-problem/tree/proxy and I was able to see proxy settings being added:
```
[DEBUG]   (f) keepContainer = false
[DEBUG]   (f) logStdout = false
[DEBUG]   (f) maxConnections = 100
[DEBUG]   (f) outputDirectory = target/docker
[DEBUG]   (f) project = MavenProject: io.fabric8.dmp.samples:demp-sample-zero-config:0.28-SNAPSHOT @ /home/Rohaan/work/repos/demp-link-problem/test/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: io.fabric8.dmp.samples:demp-sample-zero-config:0.28-SNAPSHOT @ /home/Rohaan/work/repos/demp-link-problem/test/pom.xml]
[DEBUG]   (f) removeVolumes = false
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@488b50ec
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@6090f3ca
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipBuild = false
[DEBUG]   (f) skipExtendedAuth = false
[DEBUG]   (f) skipMachine = false
[DEBUG]   (f) skipTag = false
[DEBUG]   (f) sourceDirectory = src/main/docker
[DEBUG]   (f) useColor = true
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
[DEBUG] DOCKER> Build args set {}
[DEBUG] DOCKER> Build args set {}
[DEBUG] DOCKER> Build args set {docker.buildArg.http_proxy=http://127.0.0.1:3001}
[INFO] Building tar: /home/Rohaan/work/repos/demp-link-problem/test/target/docker/samples/demp-sample-zero-config/latest/tmp/docker-build.tar
[INFO] DOCKER> [samples/demp-sample-zero-config:latest]: Created docker-build.tar in 29 milliseconds
[INFO] DOCKER> [samples/demp-sample-zero-config:latest]: Built image sha256:291cc
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.967 s
[INFO] Finished at: 2019-04-05T21:26:36+05:30
[INFO] ------------------------------------------------------------------------
~/work/repos/demp-link-problem/test : $ 
```

**Comment by rohanKanojia** [comment]
@jakub-bochenski : Could you please check if it works for you? This is rudimentary just to make proxy setting work. Would be awesome if you could share feedback on what other values shall be read from local docker config.

**Comment by jakub-bochenski** [comment]
> This is rudimentary implementation just to make proxy setting work. Would be awesome if you could share feedback on what other values shall be read from local docker config.

I think you only extract http_proxy now. There is also related https_proxy and no_proxy (and possibly ftp_proxy?).
On the other hand, I would rather keep this PR focused on the proxy settings and not add anything more from  the config. Let's get this merged and then work on including more

**Comment by rohanKanojia** [comment]
@jakub-bochenski :Yeah, I saw those... but I wasn't aware that other two can also be used as arguments in buildservice. Okay, let me add them too

**Comment by jakub-bochenski** [comment]
Here is a list of pre-defined build args https://docs.docker.com/v17.09/engine/reference/builder/#predefined-args (ftp_proxy included)

**Comment by rhuss** [comment]
Thanks @rohanKanojia and @jakub-bochenski . Looks good to me !

**Pull request merged**
