### PR TITLE
Added support for 'cachefrom' when building an image

### LINKED ISSUE #1132: Add support for cachefrom
Adding support for `cachefrom` should improve build time when running in a CI DinD environment. This field is supported as of API v1.25. 

The POM configuration block should take a list of image names, possibly as one comma delimited string. The `cachefrom` field would then be added to the build request as a JSON array of strings.

Ideally, the build process would pull each image before submitting the image build request.

### PR DESCRIPTION
**Pull request by llowrey**
Fixes #1132 :This is my initial attempt. I'm not sure how to test it so this effort is incomplete. This PR relates to issue

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks for the PR ! To complete it, I'd recommend:

* Add a test method to `BuildConfigTest` to ensure that the generated JSON is as you expect
* Add to the build options in the [docs](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/asciidoc/inc/build/_configuration.adoc)
* Add an entry in doc/changelog.md

We don't have really any integration tests, so its ok to have only this unit test.

I'm planning to make a release this evening (CET), so we could still include this PR if you have time to implement that parts today.

thanks !

**Comment by rohanKanojia** [comment]
@llowrey : Is this till a WIP?

**Comment by llowrey** [comment]
This should be done. I had made the changes requested by @rhuss.

**Comment by rohanKanojia** [comment]
@llowrey: ah, okay. Adding WIP label then

**Comment by rohanKanojia** [comment]
@llowrey : Polite ping, still working on this patch? We're preparing to release and I would like to have this in. Could you please find time to update this? Otherwise we would update it whenever we get time.

**Comment by llowrey** [comment]
This should have been done as of my commit on Dec-14. Is there something else I need to do?

**Comment by rohanKanojia** [comment]
@llowrey : oh, sorry. I misunderstood your previous statement. Removing WIP then

**Comment by llowrey** [comment]
Unfortunately, I do not have any more time to put toward this so I am abandoning this PR. Sorry for the bother and thank you for considering it.

**Comment by rohanKanojia** [comment]
@llowrey : ah, It's okay someone else can pick this up. It's pretty much done, right? What are things that need to be fixed in order to get this merged?

**Comment by rhuss** [comment]
@rohanKanojia actually I think its only the integration into the PropertyHandler (including a test). Otherwise the PR looks good to me.

**Comment by llowrey** [comment]
@rohanKanojia: I don't know. @rhuss mentioned ```PropertyHandler``` and ```PropertyHandlerTest``` but I couldn't figure out what to do after poking around for a few minutes. I'm just not familiar enough with the whole codebase to know what else needs to be done. The feature works, at least in my use case. It seems what remains is to do whatever else is required for it to be properly integrated into the codebase.

**Comment by rhuss** [comment]
@llowrey no worries we can pick that up, if this is ok for you.

**Comment by rhuss** [comment]
@llowrey thanks for the PR btw, really appreciated !

**Pull request merged**
