### PR TITLE
update samples aggregator pom; use build-nofork in lifecycles

### PR DESCRIPTION
**Pull request by chonton**

### CODE REVIEW

**Comment by chonton** [comment]
lifecycles should use build-nofork to prevent duplicate goal executions.

**Comment by rhuss** [comment]
Thanks ! Will review and very likely integrate next week.

**Comment by rhuss** [comment]
Sorry, I messed up this PR while reorganizing branches. In the future d-m-p will adapt the modell of other fabric8 projects to work against `master` directly, without the usage of an `integration` branch. The documentation will build on an extra branch `dmp.fabric8.io`.

Have to think how to resolve this ;-|

**Comment by rhuss** [comment]
@chonton  if you don't mind, could you please recreate the PR against the `fabric8io:master` branch ? I think that's the simplest solution.

Thanks and sorry for the inconvenience ...

**Comment by chonton** [comment]
replaced with #662

**Pull request closed without merging**
