### PR TITLE
Bump Http Client to version 4.5.5

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
cc @rhuss tests are good 

Tests run: 420, Failures: 0, Errors: 0, Skipped: 5

the job has troubles.

**Comment by rhuss** [comment]
@oscerd let me check that later when I'm back home. Thanks for taking care ;-)

[btw, what are you doing the next four weeks ? ;-P Just kidding, its a unique occasion in lifetime that I can't miss to bug my italian friends. Knowing that it will hit me hard in the future when such a faux-pas happens to us]

**Comment by oscerd** [comment]
@rhuss the last for coaches the Italian team has had (Prandelli,Conte,Ventura and Mancini) are on top of my hate list :-) So in the last years I never cared about National team :-) This year I will support Nigeria  :-) Btw I don't think Germany will ever miss a World Cup :-)

**Comment by oscerd** [comment]
@rhuss any news on this?

**Comment by rhuss** [comment]
Sorry, forgot up ths one. Going to merge ASAP.

**Pull request merged**
