### PR TITLE
Update jnr-unixsocket 0.21->0.22.

### PR DESCRIPTION
**Pull request by 0t4ku**
Resolves issues similar to #1119.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@0t4ku : Thanks for contributing :+1: Could you please add a line to changelog also?

**Comment by 0t4ku** [comment]
Updated changelog.

**Comment by 0t4ku** [comment]
When is 0.28.1 scheduled for release? I'm hitting this problem consistently using this docker version:

$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by rohanKanojia** [comment]
@0t4ku : Can we close #1119 now?

**Comment by 0t4ku** [comment]
@rohanKanojia not sure. For me the issue is fixed by this update but not 100% it's also fixed for the issue reported previously. @akoshman @r4v5 can you try with this change?

**Comment by 0t4ku** [comment]
The problem reappeared for me even with 0.22. :-|

**Comment by 0t4ku** [comment]
> The problem reappeared for me even with 0.22. :-|

Ignore the above. I was testing by mistake with 0.21. It works fine for me with 0.22.

Can you please release a new version with this update soon(ish)? Without it my build gets stuck on every run.

**Comment by rohanKanojia** [comment]
I'm just a helper. @rhuss is the owner of this project and is super busy these days. He can give you an ETA of release

**Pull request merged**
