### PR TITLE
Enhance Fix #541: Allow @sha256 digest for tags in FROM

### LINKED ISSUE #541: Allow @sha256 digest for tags in FROM
When I try to use a digest tag in my Dockerfile FROM: such as "FROM: mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925" I get this:

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.14:build (docker-build) on project kestrel-docker: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.15.14:build failed: Given repository name 'mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925' is invalid:
[ERROR] \* image part 'mytomcat@sha256' doesn't match allowed pattern '(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9])(?:(?:.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_(?:/[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_)?'

I see various mentions in docker re: digest usage and our docker-compose.yml uses it just fine. Do the regex's need to be updated?

### PR DESCRIPTION
**Pull request by mmkonrad**
ImageName.java and respective test class adjusted to be able to handle
image names with tag AND sha256 digest like:
image_name:image_tag@sha256<digest>

Signed-off-by: Marcus Konrad <M.M.Konrad@web.de>

### CODE REVIEW

**Comment by mmkonrad** [comment]
This is actually part of the [Fabric8 MVN Plugin Issue 1386](https://github.com/fabric8io/fabric8-maven-plugin/issues/1386)

**Comment by rohanKanojia** [comment]
@mmkonrad : Thanks for the PR :+1: Will look soon ...

**Comment by rohanKanojia** [comment]
@mmkonrad : What does this PR do? I don't see any changes other than indentation fixes. Is it still a WIP? Could you please add a test to validate desired behavior?

**Comment by mmkonrad** [comment]
In the Fabric8 MVN Plugin thread I wrote, that I probably have to close and reopen the PR since I didn't squash the commits.
When I look at it I see two commits and two files changed. The relevant changes are where made to the ImageName.java and I also added some tests in ImageNameTest.java.

**Comment by mmkonrad** [comment]
I am going to close this PR and reopen it. hopefully without any indent issues

**Pull request closed without merging**
