### PR TITLE
#818 Update the required version of docker-compose in DockerComposeCo…

### PR DESCRIPTION
**Pull request by jimusbobus**
…nfigHandler to be 2.1

I had a look to see if i could add a unit test in DockerComposeConfigHandlerTest but could not see any existing tests, I'd like to add some if possible, where would be a good place to start?

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks !

you are right, the DockerComposeConfigHandlerTest is currently not functional. You could have a look at PropertyConfigHandlerTest for a similar test or give DocerComposConfigHandlerTest a try (sorry havent looked at it for a while)

**Comment by rhuss** [comment]
We use JMockit as a mocking framework, if you need to mock up some stuff.

**Comment by rhuss** [comment]
[merge]

**Comment by jimusbobus** [comment]
ok thanks, i will look into adding tests later :)

do you know when this will get released?

**Comment by rhuss** [comment]
gimme a bit, we can cut a release early next week.

**Comment by jimusbobus** [comment]
no rush :)  just wondered, its useful not essential.

**Pull request merged**
