### PR TITLE
use credential helper if defined

### PR DESCRIPTION
**Pull request by denisa**
Signed-off-by: Denis N. Antonioli <d_n_antonioli@yahoo.com>

Fix issue #806.
In need of feedback, especially any idea on how to test this…

I have only performed happy-path tests manually until now.

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks ! I will have a look asap, but will be on PTO this week, so might take a bit. Please ping me, if I forget this after this week.

**Comment by denisa** [comment]
any chance of getting this reviewed in a neat future?

**Comment by rhuss** [comment]
sorry, still under full load with other stuff ;-( But I definitely consider this PR for the next release, which is not so far away. Hopefully on the weekend, but if not, it still might take three weeks as I'm fully booked with other work for the next time.

really sorry, but it's not forgotten ...

**Comment by rhuss** [comment]
I rebased and made some minor updates.

Look good to me, lets merge it (sorry for the ultra long delay).

wrt testing: I think we could do this by including some shell scripts into the code which are written out to a tempdir during the test and then mock the `.dockercfg` read to point to this shell scripts which return expected JSON when called as external command. It's a bit involved and only works for certain environments (unix like), but might be worth to try. If you feel fancy, you can give it a try (I'm unfortunately still under high load so have no time for this :(

Thanks a lot ! (and sorry again, you can expect a release on the weekend)

**Comment by rhuss** [comment]
@denisa 0.23.0 is out. Thanks for your contribution !

**Pull request merged**
