### PR TITLE
Lots of warnings are displayed when assembly.mode is tar or tgz when building on windows

### PR DESCRIPTION
**Pull request by zoltanersek**
Addressing issue #591

### CODE REVIEW

**Comment by rhuss** [comment]
Thanks a lot. I'm currently on the road but will be back soon. Will check out the PR ASAP.

**Comment by rhuss** [comment]
Thanks a lot, makes sense to add this option.

Could you please do me the following favours:

* Please sign-off your commit as described in [Contributing](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/contributing.md)
* Please add some documentation along with the possible values for `longTarFileMode`. These should go into https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/asciidoc/inc/build/_assembly.adoc

Thanks !

**Comment by zoltanersek** [comment]
Thanks. I've signed the commit and added the documentation.

**Comment by rhuss** [comment]
Thanks a lot, will include the PR in the next release (probably end of the week)

**Pull request merged**
