### PR TITLE
Add ShmSize support for "docker run" command

### PR DESCRIPTION
**Pull request by obigard**
Need to add "--shm-size" property for "docker run" command

### CODE REVIEW

**Comment by rhuss** [comment]
awesome !

Two things:

* Could you please add to the documentation in https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/manual/docker-start.md (look for 'Memory') ?
* Could you please add the support also to the property configuration handler like in https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java#L104 ?

would be awesome if you could add this, too. btw, we are planning a new release of d-m-p tomorrow or so.

**Comment by obigard** [comment]
I'll do it...

**Comment by obigard** [comment]
I've got a question: when implementing this "shm-size" enhancement, I checked the JSon data that should be sent to Docker Remote API. And it seems that the "Memory" and "MemorySwap" should be placed under "HostConfig" tag, which doesn't seem to be the case in your "ContainerCreateConfig"...
Am I wrong? Shouldn't tags "memory" and "memorySwap" be placed in "ContainerHostConfig" class instead of "ContainerCreateConfig"?

Thanks

**Comment by rhuss** [comment]
damned, you are right. wonder why nobody noticed that yet. Guess the tests could be improved. 

thanks for the heads up I will fix this while I'm merging in your PR.

Thanks a lot !

**Comment by obigard** [comment]
Do you know why the Jenkins check is failing???

**Comment by rhuss** [comment]
looks like some internal issue with the git merge plugin. will check that later. but 2 out of 3 are good enough ;)

**Comment by obigard** [comment]
ah, ok :-)

**Pull request merged**
