### PR TITLE
fixed issue: #1359

### LINKED ISSUE #1359: Build failure with DOCKER_HOST=tcp://...
### Description

Unable to build when environment variable `DOCKER_HOST` references **TCP** protocol

### Info

* d-m-p version : 0.33.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```
* Docker version : 19.03.8
* running Docker Desktop on OS X 10.14 (therefore _no_ **docker-machine**)

#### Normal Use Case

- local build works fine in normal use-case: `mvn docker:build`
  i.e. there are _no_ `DOCKER_*` environment variables set at all

#### Local Kubernetes (K8s) Cluster Use Case

- trying to run local build by pointing Docker build to local [minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) cluster, via:
  ```
  $ eval $(minikube docker-env)
  ```
  which results in setting these environment variables:
  ```
  $ export DOCKER_TLS_VERIFY="1"
  $ export DOCKER_HOST="tcp://127.0.0.1:32770"
  $ export DOCKER_CERT_PATH="/Users/alan/.minikube/certs"
  $ export MINIKUBE_ACTIVE_DOCKERD="minikube"
  ```
- local build with `docker build ./src/main/docker/` works fine
- local build with `mvn docker:build` fails with error:
  ```
  [ERROR] DOCKER> Unable to check image [repo.example.com:5001/docker-releases/base-image:1.0] : Client sent an HTTP request to an HTTPS server. (Bad Request: 400) [Client sent an HTTP request to an HTTPS server. (Bad Request: 400)]
  ```
- Dockerfile has:
  ```
  FROM repo.example.com:5001/docker-releases/base-image:1.0
  ...
  ```
- URL works fine from HTTPs: https://repo.example.com:5001/docker-releases/base-image:1.0
- if you change the `DOCKER_HOST` environment variable from **TCP** protocol to **HTTPs** protocol:
  ```
  $ export DOCKER_HOST="https://127.0.0.1:32770"
  ```
  then local build fails with: `unable to resolve docker endpoint: Invalid bind address format: https://127.0.0.1:32770`
  but then `mvn docker:build` works fine

##### Problem

Why is it that `docker build ./src/main/docker/` works fine but `mvn docker:build` fails when `DOCKER_HOST` environment variable uses **TCP** protocol? Why through the Maven Docker plugin it is trying HTTP instead of HTTPs but on Docker CLI it works fine?

##### Summary

No environment variables set:
- Maven Docker build works fine
- Docker CLI build works fine

`export DOCKER_HOST="tcp://127.0.0.1:32770"`
- Maven Docker build fails with: `Client sent an HTTP request to an HTTPS server. (Bad Request: 400)`
- Docker CLI build works fine

`export DOCKER_HOST="https://127.0.0.1:32770"`
- Maven Docker build works fine
- Docker CLI build fails with: `unable to resolve docker endpoint: Invalid bind address format: https://127.0.0.1:32770`

### PR DESCRIPTION
**Pull request by alan-czajkowski**
fixes #1359

### CODE REVIEW

**Comment by alan-czajkowski** [comment]
@rhuss this is a relatively easy fix, are you able to merge it in and release?

**Comment by rhuss** [comment]
Sounds legit to me. Let's try how it goes and if people start complaining if this is not backwards compatible ...

**Comment by alan-czajkowski** [comment]
@rhuss when is the next release?

**Comment by alan-czajkowski** [comment]
@rhuss any chance we can get a new release?

**Comment by rhuss** [comment]
yes, i will work my way through the open pull requests and then eventually make a new release, probably towards the end of next week.

**Comment by alan-czajkowski** [comment]
@rhuss release coming soon?

**Comment by rhuss** [comment]
you got me :) Unfortunately I only can work on dmp on the weekend, so I will try this weekend again.

**Comment by nodece** [comment]
This is breaking changes and affects too many people using this plugin, is there any way we can skip not using HTTPS?

**Comment by alan-czajkowski** [comment]
@nodece what do you mean not using HTTPs? it's the standard and this fix genuinely improves the plugin, can you describe in what situation this fix is bad for you?

**Comment by nodece** [comment]
@alan-czajkowski 

>what do you mean not using HTTPs?

Right!

>  it's the standard and this fix genuinely improves the plugin, can you describe in what situation this fix is bad for you?

I understand this, some times I want to use the HTTP protocol instead of HTTPS protocol to reduce the config.

**Comment by alan-czajkowski** [comment]
@nodece can you describe a situation where HTTP is preferred over HTTPs (please explain in great detail)?

**Comment by nodece** [comment]
> @nodece can you describe a situation where HTTP is preferred over HTTPs (please explain in great detail)?

I know your idea that using HTTPS is more secure, we should abide by using HTTPS in any case. Sometimes we use HTTP  instead of HTTPS, we don't need to config the TLS. This is the only reason I switch to the HTTP.

**Pull request merged**
