### PR TITLE
Use https://index.docker.io/v1/ as default server registry

### LINKED ISSUE #1574: buildx push leads to "server message: insufficient_scope: authorization failed"
### Description

We tried to integrate cross arch images via this plugin into one of our OSS projects. In general it works but pushing to docker hub fails for some reason.

The project (and buildx integration) can be found here: https://github.com/factcast/factcast/blob/issue2057/factcast-docker/pom.xml

If I run `mvn docker:push` in this module the output looks like this:
```
[INFO] --- docker-maven-plugin:0.40.1:push (default-cli) @ factcast-docker ---
[INFO] DOCKER> docker --config /factcast-docker/target/docker/otbe/factcast2/docker buildx create --driver docker-container --name dmp_otbe_factcast2
[INFO] DOCKER> dmp_otbe_factcast2
[INFO] DOCKER> docker --config /factcast/factcast-docker/target/docker/otbe/factcast2/docker buildx build --progress=plain --builder dmp_otbe_factcast2 --platform linux/amd64,linux/arm64 --tag otbe/factcast2:latest --tag otbe/factcast2 --push --cache-to=type=local,dest=/factcast/factcast-docker/target/docker/otbe/factcast2/cache --cache-from=type=local,src=/factcast/factcast-docker/target/docker/otbe/factcast2/cache --file=/factcast/factcast-docker/target/docker/otbe/factcast2/tmp/docker-build/Dockerfile /factcast/factcast-docker/target/docker/otbe/factcast2/tmp/docker-build
[INFO] DOCKER> #1 [internal] booting buildkit
[INFO] DOCKER> #1 pulling image moby/buildkit:buildx-stable-1
[INFO] DOCKER> #1 pulling image moby/buildkit:buildx-stable-1 1.7s done
[INFO] DOCKER> #1 creating container buildx_buildkit_dmp_otbe_factcast20
[INFO] DOCKER> #1 creating container buildx_buildkit_dmp_otbe_factcast20 0.7s done
[INFO] DOCKER> #1 DONE 2.4s
[INFO] DOCKER> 
[INFO] DOCKER> #2 [internal] load .dockerignore
[INFO] DOCKER> #2 transferring context: 2B done
[INFO] DOCKER> #2 DONE 0.0s
[INFO] DOCKER> 
[INFO] DOCKER> #3 [internal] load build definition from Dockerfile
[INFO] DOCKER> #3 transferring dockerfile: 359B done
[INFO] DOCKER> #3 DONE 0.0s
[INFO] DOCKER> 
[INFO] DOCKER> #4 [linux/arm64 internal] load metadata for docker.io/library/openjdk:11-slim
[INFO] DOCKER> #4 DONE 2.0s
[INFO] DOCKER> 
[INFO] DOCKER> #5 [linux/amd64 internal] load metadata for docker.io/library/openjdk:11-slim
[INFO] DOCKER> #5 DONE 2.1s
[INFO] DOCKER> 
[INFO] DOCKER> #6 importing cache manifest from local:10452827612444733491
[INFO] DOCKER> #6 DONE 0.0s
[INFO] DOCKER> 
[INFO] DOCKER> #7 [linux/arm64 1/4] FROM docker.io/library/openjdk:11-slim@sha256:4caea2bf47d4edf9e369d716040e0e803e528033bb005bf210bafe0dab1970f1
[INFO] DOCKER> #7 resolve docker.io/library/openjdk:11-slim@sha256:4caea2bf47d4edf9e369d716040e0e803e528033bb005bf210bafe0dab1970f1 0.0s done
[INFO] DOCKER> #7 DONE 0.0s
[INFO] DOCKER> 
[INFO] DOCKER> #8 [linux/amd64 1/4] FROM docker.io/library/openjdk:11-slim@sha256:4caea2bf47d4edf9e369d716040e0e803e528033bb005bf210bafe0dab1970f1
[INFO] DOCKER> #8 resolve docker.io/library/openjdk:11-slim@sha256:4caea2bf47d4edf9e369d716040e0e803e528033bb005bf210bafe0dab1970f1 0.0s done
[INFO] DOCKER> #8 sha256:e45dadc191219f153f9cf4a382217cd22957cf80824baeffbe367d5fbf4eb25c 211B / 211B 0.2s done
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 0B / 204.24MB 0.2s
[INFO] DOCKER> #8 sha256:4b4dc029a36926590a5070a9a58443942497e3b2d48cff116b8b15004d386a40 0B / 1.58MB 0.2s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 0B / 31.38MB 0.2s
[INFO] DOCKER> #8 sha256:4b4dc029a36926590a5070a9a58443942497e3b2d48cff116b8b15004d386a40 1.58MB / 1.58MB 0.4s done
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 3.15MB / 31.38MB 0.8s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 10.49MB / 204.24MB 0.9s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 5.24MB / 31.38MB 0.9s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 7.34MB / 31.38MB 1.1s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 9.44MB / 31.38MB 1.2s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 12.58MB / 31.38MB 1.5s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 14.68MB / 31.38MB 1.7s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 20.97MB / 204.24MB 1.8s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 16.78MB / 31.38MB 1.8s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 19.14MB / 31.38MB 2.0s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 22.02MB / 31.38MB 2.1s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 24.12MB / 31.38MB 2.3s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 26.21MB / 31.38MB 2.4s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 28.31MB / 31.38MB 2.6s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 31.46MB / 204.24MB 2.7s
[INFO] DOCKER> #8 sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 31.38MB / 31.38MB 2.7s done
[INFO] DOCKER> #8 extracting sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 41.94MB / 204.24MB 3.3s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 53.48MB / 204.24MB 3.8s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 65.01MB / 204.24MB 4.2s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 75.50MB / 204.24MB 4.7s
[INFO] DOCKER> #8 extracting sha256:b85a868b505ffd0342a37e6a3b1c49f7c71878afe569a807e6238ef08252fcb7 2.1s done
[INFO] DOCKER> #8 extracting sha256:4b4dc029a36926590a5070a9a58443942497e3b2d48cff116b8b15004d386a40
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 87.03MB / 204.24MB 5.1s
[INFO] DOCKER> #8 extracting sha256:4b4dc029a36926590a5070a9a58443942497e3b2d48cff116b8b15004d386a40 0.2s done
[INFO] DOCKER> #8 extracting sha256:e45dadc191219f153f9cf4a382217cd22957cf80824baeffbe367d5fbf4eb25c 0.0s done
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 98.57MB / 204.24MB 5.6s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 110.10MB / 204.24MB 6.0s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 121.63MB / 204.24MB 6.5s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 133.17MB / 204.24MB 6.9s
[INFO] DOCKER> #8 ...
[INFO] DOCKER> 
[INFO] DOCKER> #9 [internal] load build context
[INFO] DOCKER> #9 transferring context: 148.22MB 7.2s done
[INFO] DOCKER> #9 DONE 7.3s
[INFO] DOCKER> 
[INFO] DOCKER> #10 [linux/arm64 2/4] RUN mkdir /config
[INFO] DOCKER> #10 CACHED
[INFO] DOCKER> 
[INFO] DOCKER> #11 [linux/arm64 3/4] RUN mkdir /log
[INFO] DOCKER> #11 CACHED
[INFO] DOCKER> 
[INFO] DOCKER> #12 [linux/arm64 4/4] COPY /target/factcast.jar /factcast.jar
[INFO] DOCKER> #12 CACHED
[INFO] DOCKER> 
[INFO] DOCKER> #8 [linux/amd64 1/4] FROM docker.io/library/openjdk:11-slim@sha256:4caea2bf47d4edf9e369d716040e0e803e528033bb005bf210bafe0dab1970f1
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 144.70MB / 204.24MB 7.4s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 160.43MB / 204.24MB 8.0s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 171.97MB / 204.24MB 8.4s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 187.70MB / 204.24MB 9.0s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 203.42MB / 204.24MB 9.6s
[INFO] DOCKER> #8 sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 204.24MB / 204.24MB 9.8s done
[INFO] DOCKER> #8 extracting sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6
[INFO] DOCKER> #8 extracting sha256:6a3a8ac322c4765e994b2b00f4ef9c7f3b31ac41dcc00e176ab181a5e2a135a6 1.6s done
[INFO] DOCKER> #8 DONE 11.5s
[INFO] DOCKER> 
[INFO] DOCKER> #13 [linux/amd64 2/4] RUN mkdir /config
[INFO] DOCKER> #13 DONE 0.6s
[INFO] DOCKER> 
[INFO] DOCKER> #14 [linux/amd64 3/4] RUN mkdir /log
[INFO] DOCKER> #14 DONE 0.1s
[INFO] DOCKER> 
[INFO] DOCKER> #15 [linux/amd64 4/4] COPY /target/factcast.jar /factcast.jar
[INFO] DOCKER> #15 DONE 0.3s
[INFO] DOCKER> 
[INFO] DOCKER> #16 exporting to image
[INFO] DOCKER> #16 exporting layers
[INFO] DOCKER> #16 exporting layers 3.1s done
[INFO] DOCKER> #16 exporting manifest sha256:8743ee184669513f2f80f0283a997daa79c3000a133b57e3b51a626f5c8a6e99 0.0s done
[INFO] DOCKER> #16 exporting config sha256:961e2ff74e2329b007c9eb2d4ffb567afc195037f04813d5773673b86a456cbb done
[INFO] DOCKER> #16 exporting manifest sha256:46962c4edf7dae5688d96f6d53da1d3eca41ee2b77347cdd2abedaf6e46a6181 done
[INFO] DOCKER> #16 exporting config sha256:7e47423dee639046aee16b20387cbd99d42ec0b1f1d8fcec75d90df422e152fd done
[INFO] DOCKER> #16 exporting manifest list sha256:ac1d6314a21def51dc3098ba28abed519eddbecd0bf77d2278853e5d7ad8476b done
[INFO] DOCKER> #16 pushing layers
[INFO] DOCKER> #16 pushing layers 1.3s done
[INFO] DOCKER> #16 ERROR: server message: insufficient_scope: authorization failed
[INFO] DOCKER> ------
[INFO] DOCKER>  > exporting to image:
[INFO] DOCKER> ------
[INFO] DOCKER> error: failed to solve: server message: insufficient_scope: authorization failed
[INFO] DOCKER> docker --config /factcast/factcast-docker/target/docker/otbe/factcast2/docker buildx rm dmp_otbe_factcast2
```

However if I copy the generated docker commands from the maven output and execute them manually it works.

```
$ docker --config /factcast/factcast-docker/target/docker/otbe/factcast2/docker buildx create --driver docker-container --name dmp_otbe_factcast2
dmp_otbe_factcast2
```

```
$ docker --config /factcast/factcast-docker/target/docker/otbe/factcast2/docker buildx build --progress=plain --builder dmp_otbe_factcast2 --platform linux/amd64,linux/arm64 --tag otbe/factcast2:latest --tag otbe/factcast2 --push --cache-to=type=local,dest=/factcast/factcast-docker/target/docker/otbe/factcast2/cache --cache-from=type=local,src=/factcast/factcast-docker/target/docker/otbe/factcast2/cache --file=/factc
ast/factcast-docker/target/docker/otbe/factcast2/tmp/docker-build/Dockerfile /factcast/factcast-docker/target/docker/otbe/factcast2/tmp/docker-build

.....

#17 exporting to image
#17 pushing layers 21.3s done
#17 pushing manifest for docker.io/otbe/factcast2:latest@sha256:7f1546b34e9cf86a7bc632c7a9e07660f91331e120821548b6ca6f61e7c7787b
#17 pushing manifest for docker.io/otbe/factcast2:latest@sha256:7f1546b34e9cf86a7bc632c7a9e07660f91331e120821548b6ca6f61e7c7787b 1.4s done
#17 pushing layers 1.1s done
#17 pushing manifest for docker.io/otbe/factcast2:latest@sha256:7f1546b34e9cf86a7bc632c7a9e07660f91331e120821548b6ca6f61e7c7787b 0.5s done
#17 DONE 27.6s
```

The result is here: https://hub.docker.com/repository/docker/otbe/factcast2/tags?page=1&ordering=last_updated

I just changed the image name locally (from factcast/factcast to otbe/factcast2) to not pollute our docker hub repo during my tests :)

Something similar is mentioned in https://github.com/fabric8io/docker-maven-plugin/issues/1565#issuecomment-1154661707

Any idea whats wrong with our setup? Thank you :)

### Info

* docker-maven-plugin version : 0.40.1
* Maven version (`mvn -v`) : 3.8.5 
* Docker version : 20.10.16
* Sample project : https://github.com/factcast/factcast/tree/issue2057

### PR DESCRIPTION
**Pull request by chonton**
closes #1574

### CODE REVIEW

**Comment by marcelstoer** [comment]
Shouldn't you deduce the default registry from the image name? As your docs even given an example of an image name containing registry host:port at https://dmp.fabric8.io/#ant-like-name-patterns I was expecting you'd use that when pushing the image.

**Comment by chonton** [comment]
See [Registry handling](https://dmp.fabric8.io/#registry) for how registry is determined.  If no registry is defined, then the default `docker.io` is used.  The url key for credentials of that registry is `https://index.docker.io/v1/`

**Comment by chonton** [comment]
@rohanKanojia, Please review

**Comment by marcelstoer** [comment]
Sorry, I missed that your change only affects the auth mechanism, mea culpa.

**Review by rohanKanojia — APPROVED** [review]

**Comment by derkaiserreich** [comment]
@rohanKanojia Is there an ETA for a new version of the plugin with this pr included? The latest three PRs in general would help us out a lot for our pipeline, currently we're relying on workarounds.

**Comment by rohanKanojia** [comment]
Thanks for reaching out, Let me cut a new patch release in the coming weekend.

**Comment by derkaiserreich** [comment]
Perfect, thank you!

**Pull request merged**
