### PR TITLE
Skip FROM images which are referred to by a named alias

### LINKED ISSUE #1443: Bug: Docker Multistage Build labeled stage is not detected
### Description
Mutlistage Docker Build is failing if named stage is used as a base later:

### Info

* docker-maven-plugin version: 0.34.1
* maven verison:  3.6.3

Example Dockerfile:
```
FROM centos AS first

RUN ls -la /

FROM centos as second

RUN ls -la /

# this fails
FROM second

RUN ls -la /
```

Error:
```
Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (build-docker) on project xxx-my-project-xxx Unable to pull 'second:latest' : {"message":"pull access denied for second, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"} (Not Found: 404)

```

### PR DESCRIPTION
**Pull request by davoustp**
Fixes #1443
Image alias check was performed only for the `FROM <alias1> AS <alias2>` case and not for straight `FROM <alias1>` case.

Signed-off-by: Pascal Davoust <pascal.davoust@enghouse.com>

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@davoustp : Could you please add a line to doc/changelog.md regarding this change? I think we can proceed with merge after that

**Comment by davoustp** [comment]
Sure - did not see that (I supposed the changelog was automatically generated).
Process to do that from your point of view? Just commiting the change to my own repo enough? Or do you want me to squash the two commits together and force it upstream?

**Comment by rohanKanojia** [comment]
Right now we're maintaining a changelog file: https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md

You would need to update it linking the bug you're fixing  in 0.36-SNAPSHOT section.

**Comment by davoustp** [comment]
Done.

**Pull request merged**
