### PR TITLE
buildx does not work when specifying Dockerfile location

### LINKED ISSUE #1562: "failed to read dockerfile" error with submodules, dockerfiles and buildx
### Description

I have a reasonably complicated project that uses Maven submodules and Dockerfiles for builds.  This works fine without the new `buildx` configuration but breaks using it. It crashes out with the following error:

```
[INFO] DOCKER> WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[INFO] DOCKER> WARNING: local cache import at ......./dmp-buildx-bug/module1/target/docker/dmp-buildx-bug/cache not found due to err: could not read ....../dmp-buildx-bug/module1/target/docker/dmp-buildx-bug/cache/index.json: open ....../dmp-buildx-bug/module1/target/docker/dmp-buildx-bug/cache/index.json: no such file or directory
[INFO] DOCKER> error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3293280157/Dockerfile: no such file or directory
[INFO] DOCKER> docker --config ....../dmp-buildx-bug/module1/target/docker/dmp-buildx-bug/docker buildx rm dmp_dmp-buildx-bug
```

I've simplified my config into a repo that can reproduce the issue with a simple `mvn clean package`: https://github.com/spmason/dmp-buildx-bug

Note that commenting out the `<buildx>` or `<dockerFile>` config gets past the error.  The same config also works for single-module projects

### Info

* docker-maven-plugin version : 0.40.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 11.0.12, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.3.1", arch: "x86_64", family: "mac"
```
* Docker version : Docker Desktop 4.8.2 (MacOS 12.3.1) (it also fails on our Linux build nodes so it's not mac-specific)
* If it's a bug, how to reproduce : Download the repo and run `mvn clean package`
* If it's a feature request, what is your use case : N/A
* Sample project : https://github.com/spmason/dmp-buildx-bug.git

### LINKED ISSUE #1563: usage of 'buildx' in combination with 'dockerFile' and 'contextDir' leads to 'failed to read dockerfile'
### Info

* docker-maven-plugin version : 0.40.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/maven
Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.13.0-41-generic", arch: "amd64", family: "unix"
```
* Docker version :
```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* If it's a bug, how to reproduce :
Check out the sample project and build it with 'mvn clean package'.

* Sample project : *https://github.com/dvallant/dmp-test*

### PR DESCRIPTION
**Pull request by chonton**
closes #1562
closes #1563

### CODE REVIEW

**Comment by dvallant** [comment]
@chonton Dockerfile is now found but there is another issue related to '<contextDir>':
```
[INFO] DOCKER> #7 [linux/amd64 2/2] COPY target/docker/foo.txt /
[INFO] DOCKER> #7 ERROR: failed to calculate checksum of ref k2v3iuadhdiwks1kmw9bm5dye::mrkgs48ls17sqn4una1xc9qkw: failed to walk /tmp/buildkit-mount535766485/target/docker: lstat /tmp/buildkit-mount535766485/target/docker: no such file or directory
```
see https://github.com/dvallant/dmp-test

**Comment by rohanKanojia** [comment]
@dvallant : Please raise a PR against @chonton 's branch

**Comment by spmason** [comment]
I've tested this locally but per @dvallant's comment COPY commands aren't working as expected.  I'm not using an explicit `<contextDir>` though, I'm just assuming that the context is going to be set to the folder that the `Dockerfile` is in, so I think this is a separate issue and that fix won't work for me

This is because both changes set the context to`buildDirs.getOutputDirectory().getAbsolutePath())` when not explicitly set, whereas I _think_ it should be set to the Dockerfile's parent directory if one has been given. At least that would preserve the behaviour of DMP without the buildx config, and maybe `docker buildx build` itself but I may be wrong and that's changed in buildx?

**Comment by chonton** [comment]
@spmason, If you remove <platforms> from this project, I suspect it will still fail.

**Comment by chonton** [comment]
This is going to be difficult to resolve.  Currently, dmp architecture involves creating a tar of the context. I have not discovered a way to directly use a tar as a context. Instead, the buildx service 'cheats' by using one of the sources for creating the tar.  Solution may be to untar the traditionally built context somewhere.

**Comment by chonton** [comment]
@spmason please try this commit

**Comment by afranken** [comment]
@chonton just built your commit locally (with a COPY command in the Dockerfile) and I can confirm that the build works for me.

I do however experience a different problem which I just filed as #1566

**Comment by spmason** [comment]
Hey @chonton - this branch now works for my test repo, but if I try it on my actual project I get an error:

```
[INFO] Expanding: <parent>>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build.tar.gz into <parent>>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build
[INFO] DOCKER> docker --config <parent>>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/docker buildx rm dmp_<repo>_<module>_LOCAL-SNAPSHOT
[ERROR] DOCKER> Cannot extract archive <parent>>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build.tar.gz [Error while expanding <parent>>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build.tar.gz]
......
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.41.0-SNAPSHOT:build (default) on project <module>: Cannot extract archive <parent>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build.tar.gz: Error while expanding <parent>/<module>/target/docker/<repo>/<module>/LOCAL-SNAPSHOT/tmp/docker-build.tar.gz: Error detected parsing the header: Invalid byte 92 at offset 0 in '\�Y��
[ERROR] ' len=8
[ERROR] -> [Help 1]
```

However, I can extract the archive using `tar xzf path>` just fine...

**Comment by spmason** [comment]
Oh OK. It was because I was specifying `<compression>gzip</compression>` in my `<build>` section.  I don't need that, so I've simply removed it

**Comment by spmason** [comment]
I've found one more minor gotcha / change in behaviour.  One of my modules was failing to build with this error:

```
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref <blah>: "/maven": not found
```

My context folder looked fine. Turns out it wasn't technically dmp's fault, my `.dockerignore` was overly restrictive and blocking the `maven/` folder in the context (per https://stackoverflow.com/a/67391784/10386550)

As this module builds fine without buildx I guess this is a change in behaviour that might catch people out.  Though it feels to me like this behaviour is "more correct".

However maybe deleting `.dockerignore` from the context folder would bring buildx behaviour inline with the regular behavour?

**Comment by chonton** [comment]
@spmason, compression should be fixed with this version
@rohanKanojia, please review and merge

**Comment by spmason** [comment]
Thanks @chonton - I can confirm that this is all working for me now

**Comment by saravanaa14** [comment]
@chonton This PR also fixes https://github.com/fabric8io/docker-maven-plugin/issues/1565 . Would you mind sharing when we can expect a release version for this?

**Comment by chonton** [comment]
Releases are handled by @rohanKanojia.  I do not know his schedule.

**Comment by rohanKanojia** [comment]
Sorry for the delay guys, let me merge these and cut a patch release today

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
